version: '2'
services:
  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
  # mosbot:
  #   image: dtgoitia/mosbot:latest
  #   environment:
  #     DATABASE_URL: postgresql://postgres@postgres/postgres
  #   depends_on:
  #     - postgres
