apiVersion: v1
name: mosbot
description: Master of Soundtrack bot
version: 0.0.1
appVersion: 0.0.1
home: https://github.com/txomon/mosbot
sources:
  - https://github.com/txomon/mosbot
keywords:
  - bot
  - mosbot
  - master of soundtrack
maintainers:
  - name: txomon
    email: javierdo1@gmail.com
